name: Build and Publish Exe
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build Exe
      shell: pwsh
      run: |
        $env:TAG_NAME = '${{ github.ref_name }}'
        pyinstaller --onefile --noconsole --add-data "tray_icon.png;." --add-data "emojis.json;." emoji_picker.py -n "EmojiPicker_$env:TAG_NAME"
        Copy-Item emojis.json dist\emojis.json
        Copy-Item tray_icon.png dist\tray_icon.png
        tar.exe -a -c -f "./dist/EmojiPicker_$env:TAG_NAME.zip" -C ./dist "EmojiPicker_$env:TAG_NAME.exe" "emojis.json" "tray_icon.png"
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./dist/EmojiPicker_${{ github.ref_name }}.zip
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}

